name: townsquare
description: A microblogging app built using Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  # Default
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Fonts / Assets
  google_fonts: ^3.0.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0
  # Widgets
  gap: ^2.0.0
  infinite_scroll_pagination: ^3.1.0
  # Types
  built_value: ^8.3.0
  built_collection: ^5.1.1
  rxdart: ^0.27.3
  # General / Misc
  retry: ^3.1.0
  path: ^1.8.1
  path_provider: ^2.0.10
  url_launcher: ^6.1.2
  auto_route: ^4.0.1

dev_dependencies:
  # Default - Dev
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Source gen
  built_value_generator: ^8.3.0
  auto_route_generator: ^4.0.0
  # General / Misc - Dev
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true